#!/bin/bash

#################################################################
#
# seedit Software library seeding script 
#       vr 0.1
#
# Written by Corey Reichle
# 02/04/2015
# Copyright (c) 2015 by Corey Reichle.  Released under GPL 3 or later.
#
#################################################################
